#!/bin/bash
set -e

if [ ! $(command -v java) ]; then
    apt-get update
    apt-get install -y --no-install-recommends default-jre
fi

if [ ! $(command -v tox) ]; then
    apt-get install -y --no-install-recommends python-pip
    pip install --upgrade pip==6.0.3 tox==1.8.1 virtualenv==12.0.4
fi

if [ ! $(command -v zip) ]; then
    apt-get install -y --no-install-recommends zip xz-utils
fi

if [ ! $(command -v rsync) ]; then
    apt-get install -y --no-install-recommends rsync
fi
