#!/bin/bash -e

cd $(dirname $0)/..

if [ -f ./build/bootstrap.envs ];then
    . ./build/bootstrap.envs
fi

. ./scripts/common_functions

set_project_vars

if [ -L ${PACKAGE} ]; then
    rm ${PACKAGE}
fi

if [ ! -e ${PACKAGE} ]; then
    mkdir -p $(dirname $PACKAGE)
    ln -s $(pwd) $PACKAGE
fi

VERSION=$(git tag -l --contains HEAD)
if [ -z "$VERSION" ]; then
    VERSION=$(git rev-parse --short HEAD)
fi

echo export GOPATH=$GOPATH
echo VERSION=$VERSION

go build -ldflags="-w -X github.com/rancherio/rancher-compose/librcompose.VERSION $VERSION" -o bin/${PROJECT}

if [ -n "$BUILD_CROSS" ]; then
    mkdir -p dist/artifacts
    gox -os="darwin linux windows" -arch="386 amd64 arm" -output="dist/artifacts/rancher-compose_{{.OS}}-{{.Arch}}" -ldflags="-w -X github.com/rancherio/rancher-compose/librcompose.VERSION $VERSION"
fi
