#!/bin/bash

set -e
set -x

cd $(dirname $0)/..

export GOPATH=$(pwd)/Godeps/_workspace:$(pwd)/gopath

if [ ! -d ./gopath ]; then
    mkdir -p gopath/src
fi

PACKAGE=./gopath/src/$(<.package)

if [ ! -e ./src/$PACKAGE ]; then
    mkdir -p $(dirname ${PACKAGE})
    ln -s $(pwd) $PACKAGE
fi

rm -rf ./build
mkdir -p ./build ./bin

go build -o ./bin/rancher-compose
