#!/bin/bash
set -e

set_project_vars()
{
    PACKAGE=./gopath/src/$(<.package)
    PROJECT=$(basename $PACKAGE)
}

get_version()
{
    VERSION=$(git tag -l --contains HEAD | head -n 1)
    if [ -z "$VERSION" ]; then
        VERSION=$(git rev-parse --short HEAD)
    fi
}
