#!/bin/bash
set -e

set_project_vars()
{
    PACKAGE=./gopath/src/$(<.package)
    PROJECT=$(basename $PACKAGE)

    export GOPATH=$(pwd)/Godeps/_workspace:$(pwd)/gopath
}

get_version()
{
    VERSION=$(git tag -l --contains HEAD)
    if [ -z "$VERSION" ]; then
        VERSION=$(git rev-parse --short HEAD)
    fi
}
