#!/bin/bash

set -e

SCRATCH_TEMP=

trap destroy_root exit

setup_root()
{
    if [ -d /scratch ]; then
        SCRATCH_TEMP=$(mktemp -d /scratch/cattle.XXXXX)
        rsync --exclude '*.pyc' -a ./ $SCRATCH_TEMP
        pushd $SCRATCH_TEMP
    fi
}

destroy_root()
{
    if [[ -n "$SCRATCH_TEMP" && -d "$SCRATCH_TEMP" ]]; then
        popd
        rsync --delete -a ${SCRATCH_TEMP}/tests/integration/.tox ./tests/integration
        rm -rf "$SCRATCH_TEMP"
    fi
}

cd $(dirname $0)/..

. ./scripts/common_functions

set_project_vars

go test ./...

result=$(find . -name "*.go" | grep -v ./Godeps | xargs gofmt -l)
for i in $result; do
    echo Violates gofmt: $i
done

[ -n "$result" ] && exit 1

setup_root

cd tests/integration
export CATTLE_URL=${CATTLE_URL:-http://localhost:8080/v1/schemas}

if [ -e .tox ] && [ ! -e .tox/py27/include/python2.7 ]; then
    rm -rf .tox
fi

tox "$@"

echo OK
